name: sf_env
channels:
- https://repo.anaconda.com/pkgs/snowflake
- conda-forge
- nodefaults
dependencies:
- python>=3.8
- streamlit
- snowflake-snowpark-python
- plotly
- black
- flake8
- openai
- keyring
- watchdog