[tool.poetry]
name = "aimarketing"
version = "0.1.0"
description = ""
authors = ["Peter Hansen <phansen@phdata.io>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.9"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
